const countryCodes: Record<string, string> = {
  "España": "ESP",
  "Argentina": "ARG",
  "Brasil": "BRA",
  "Uruguay": "URU",
  "Colombia": "COL",
  "Chile": "CHL",
  "Perú": "PER",
  "Ecuador": "ECU",
  "Venezuela": "VEN",
  "Paraguay": "PRY",
  "Bolivia": "BOL",
  "México": "MEX",
  "Estados Unidos": "USA",
  "Canadá": "CAN",
  "Costa Rica": "CRI",
  "Panamá": "PAN",
  "Honduras": "HND",
  "El Salvador": "SLV",
  "Guatemala": "GTM",
  "Nicaragua": "NIC",
  "Cuba": "CUB",
  "República Dominicana": "DOM",
  "Puerto Rico": "PRI",
  "Jamaica": "JAM",
  "Trinidad y Tobago": "TTO",
  "Haití": "HTI",
  "Bahamas": "BHS",
  "Barbados": "BRB",
  "Alemania": "DEU",
  "Francia": "FRA",
  "Italia": "ITA",
  "Reino Unido": "GBR",
  "Inglaterra": "ENG",
  "Portugal": "POR",
  "Países Bajos": "NLD",
  "Bélgica": "BEL",
  "Suiza": "CHE",
  "Suecia": "SWE",
  "Noruega": "NOR",
  "Dinamarca": "DNK",
  "Finlandia": "FIN",
  "Irlanda": "IRL",
  "Escocia": "SCO",
  "Gales": "WAL",
  "Austria": "AUT",
  "Polonia": "POL",
  "República Checa": "CZE",
  "Eslovaquia": "SVK",
  "Hungría": "HUN",
  "Rumanía": "ROU",
  "Bulgaria": "BGR",
  "Serbia": "SRB",
  "Croacia": "HRV",
  "Bosnia y Herzegovina": "BIH",
  "Eslovenia": "SVN",
  "Montenegro": "MNE",
  "Albania": "ALB",
  "Grecia": "GRC",
  "Turquía": "TUR",
  "Ucrania": "UKR",
  "Rusia": "RUS",
  "Nigeria": "NGA",
  "Ghana": "GHA",
  "Costa de Marfil": "CIV",
  "Senegal": "SEN",
  "Camerún": "CMR",
  "Marruecos": "MAR",
  "Egipto": "EGY",
  "Túnez": "TUN",
  "Argelia": "DZA",
  "Sudáfrica": "ZAF",
  "Angola": "AGO",
  "República Democrática del Congo": "COD",
  "Kenia": "KEN",
  "Etiopía": "ETH",
  "Australia": "AUS",
  "Japón": "JPN",
  "Corea del Sur": "KOR",
  "China": "CHN",
  "India": "IND",
  "Arabia Saudita": "SAU",
  "Catar": "QAT",
  "Emiratos Árabes Unidos": "ARE",
  "Irán": "IRN",
  "Irak": "IRQ",
  "Nueva Zelanda": "NZL",
};

export function generateCode(name: string): string {
  const trimmed = name.trim();
  if (countryCodes[trimmed]) return countryCodes[trimmed];
  const clean = trimmed.replace(/[^a-zA-ZáéíóúüñÁÉÍÓÚÜÑ]/g, "");
  const upper = clean.toUpperCase();
  if (upper.length >= 3) return upper.slice(0, 3);
  return upper.padEnd(3, upper.charAt(0) || "X");
}
