// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/standings": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/verify": {
    params: {};
  };
  "/api/matches": {
    params: {};
  };
  "/api/matches/:id": {
    params: {
      "id": string;
    };
  };
  "/login": {
    params: {};
  };
  "/api/teams": {
    params: {};
  };
  "/api/teams/:id": {
    params: {
      "id": string;
    };
  };
  "/match/:id": {
    params: {
      "id": string;
    };
  };
  "/standings": {
    params: {};
  };
  "/schedule": {
    params: {};
  };
  "/team/:id": {
    params: {
      "id": string;
    };
  };
  "/index": {
    params: {};
  };
  "/teams": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/settings": {
    params: {};
  };
  "/admin/matches": {
    params: {};
  };
  "/admin/index": {
    params: {};
  };
  "/admin/teams": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/standings" | "/logout" | "/verify" | "/api/matches" | "/api/matches/:id" | "/login" | "/api/teams" | "/api/teams/:id" | "/match/:id" | "/standings" | "/schedule" | "/team/:id" | "/index" | "/teams" | "/admin" | "/admin/settings" | "/admin/matches" | "/admin/index" | "/admin/teams" | "/*";
  };
  "routes/api.standings.tsx": {
    id: "routes/api.standings";
    page: "/api/standings";
  };
  "routes/_auth.logout.tsx": {
    id: "routes/_auth.logout";
    page: "/logout";
  };
  "routes/_auth.verify.tsx": {
    id: "routes/_auth.verify";
    page: "/verify";
  };
  "routes/api.matches.tsx": {
    id: "routes/api.matches";
    page: "/api/matches" | "/api/matches/:id";
  };
  "routes/api.matches.$id.tsx": {
    id: "routes/api.matches.$id";
    page: "/api/matches/:id";
  };
  "routes/_auth.login.tsx": {
    id: "routes/_auth.login";
    page: "/login";
  };
  "routes/api.teams.tsx": {
    id: "routes/api.teams";
    page: "/api/teams" | "/api/teams/:id";
  };
  "routes/api.teams.$id.tsx": {
    id: "routes/api.teams.$id";
    page: "/api/teams/:id";
  };
  "routes/_public.tsx": {
    id: "routes/_public";
    page: "/match/:id" | "/standings" | "/schedule" | "/team/:id" | "/index" | "/teams";
  };
  "routes/_public.match.$id.tsx": {
    id: "routes/_public.match.$id";
    page: "/match/:id";
  };
  "routes/_public.standings.tsx": {
    id: "routes/_public.standings";
    page: "/standings";
  };
  "routes/_public.schedule.tsx": {
    id: "routes/_public.schedule";
    page: "/schedule";
  };
  "routes/_public.team.$id.tsx": {
    id: "routes/_public.team.$id";
    page: "/team/:id";
  };
  "routes/_public.index.tsx": {
    id: "routes/_public.index";
    page: "/index";
  };
  "routes/_public.teams.tsx": {
    id: "routes/_public.teams";
    page: "/teams";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin" | "/admin/settings" | "/admin/matches" | "/admin/index" | "/admin/teams";
  };
  "routes/admin.settings.tsx": {
    id: "routes/admin.settings";
    page: "/admin/settings";
  };
  "routes/admin.matches.tsx": {
    id: "routes/admin.matches";
    page: "/admin/matches";
  };
  "routes/admin.index.tsx": {
    id: "routes/admin.index";
    page: "/admin/index";
  };
  "routes/admin.teams.tsx": {
    id: "routes/admin.teams";
    page: "/admin/teams";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api.standings": typeof import("./app/routes/api.standings.tsx");
  "routes/_auth.logout": typeof import("./app/routes/_auth.logout.tsx");
  "routes/_auth.verify": typeof import("./app/routes/_auth.verify.tsx");
  "routes/api.matches": typeof import("./app/routes/api.matches.tsx");
  "routes/api.matches.$id": typeof import("./app/routes/api.matches.$id.tsx");
  "routes/_auth.login": typeof import("./app/routes/_auth.login.tsx");
  "routes/api.teams": typeof import("./app/routes/api.teams.tsx");
  "routes/api.teams.$id": typeof import("./app/routes/api.teams.$id.tsx");
  "routes/_public": typeof import("./app/routes/_public.tsx");
  "routes/_public.match.$id": typeof import("./app/routes/_public.match.$id.tsx");
  "routes/_public.standings": typeof import("./app/routes/_public.standings.tsx");
  "routes/_public.schedule": typeof import("./app/routes/_public.schedule.tsx");
  "routes/_public.team.$id": typeof import("./app/routes/_public.team.$id.tsx");
  "routes/_public.index": typeof import("./app/routes/_public.index.tsx");
  "routes/_public.teams": typeof import("./app/routes/_public.teams.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/admin.settings": typeof import("./app/routes/admin.settings.tsx");
  "routes/admin.matches": typeof import("./app/routes/admin.matches.tsx");
  "routes/admin.index": typeof import("./app/routes/admin.index.tsx");
  "routes/admin.teams": typeof import("./app/routes/admin.teams.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};